const PROJEKT = {
  nazev: "Rekonstrukce a přestavba rodinného domu – Podolanka",
  investor: "manželé Pěchoučkovi",
};

const ZAPISKY = [
  // ── KD 1 – 19. 5. 2026 ───────────────────────────────────────────────────
  {
    id: "kd-2026-05-19",
    cislo: 1,
    datum: "2026-05-19",
    pritomni: [
      { role: "INV", jmeno: "manželé Pěchoučkovi" },
      { role: "AD",  jmeno: "Ing. Arch. Jakub Žák" },
      { role: "TDI", jmeno: "Jakub Bednář" },
      { role: "TDI", jmeno: "Jan Nekola", kontakt: "737 283 324" },
      { role: "Zhotovitel", jmeno: "Michal Lohoyda" },
    ],
    prubehy: [
      "Provádí se: vyzdívání příček, montáž hrubých rozvodů ZTI",
      "Následné práce: betonáž stropu – dokončení, hydroizolace střechy, vyzdívky příček, rozvody ZTI",
      "BOZP: nutno kontrolovat zábradlí, otvory ve stropu a úklid",
    ],
    zmeny: [
      "Změna rozměrů interiérových dveří",
      "Poptat změnu světlíku",
      "Vyjasněn rozpor mezi PD ARCH a STAT ohledně použitých materiálů",
    ],
    ukoly: [
      {
        id: "3.1",
        termin: "2026-06-07",
        zodpovedny: "Zhotovitel",
        status: "trva",
        popis: "Předloží aktualizovaný HMG s následným postupem prací. Fáze stavby neodpovídá smluveným termínům. Nebyl splněn RPT 22.3.2026. ▸ 26.5: zhotovitel si uvědomuje, doplní do 7.6.",
      },
      {
        id: "3.3",
        termin: "2026-04-28",
        zodpovedny: "Zhotovitel",
        status: "splneno",
        popis: "U plotu na záp. straně zjištěno kanalizační vedení od sousedního objektu – bude kolidovat s oplocením. ▸ 26.5: jde o staré potrubí souseda z doby stavby – lze zrušit, úkol se vypouští.",
      },
      {
        id: "3.4",
        termin: "2026-04-28",
        zodpovedny: "TDI / AD",
        status: "splneno",
        popis: "Dotaz na ukončení drenáže okolo objektu. TDI předal dotaz na AD. Drenáž bude provedena dle PD, ukončena pod opěrnou stěnou.",
      },
      {
        id: "3.5",
        termin: "2026-04-28",
        zodpovedny: "AD",
        status: "splneno",
        popis: "AD doplnil přesné pozice koncových prvků ZTI a elektro do pohledů. V případě nejasností zašle zhotovitel dotaz.",
      },
      {
        id: "3.6",
        termin: "2026-05-19",
        zodpovedny: "Zhotovitel",
        status: "otevreno",
        popis: "Rozvody ZTI – kanalizace správně neprovedena: redukce klasickou redukcí (nikoli zkrácenou), izolace v celém rozsahu. Materiál vody zaměněn Viega → Concept – dodat tech. parametry obou + porovnání. Kotvení potrubí dle TL výrobce. ▸ 26.5: OK, napravíme.",
      },
      {
        id: "3.7",
        termin: "2026-05-19",
        zodpovedny: "Zhotovitel",
        status: "splneno",
        popis: "Otvory skrz ŽB provádět dle PD pouze odvrty – nechat schválit. Prostupy a rozvody na podkladu DPS a INT současně. ▸ 26.5: prostupy zabetonovány, splněno.",
      },
      {
        id: "3.8",
        termin: "2026-06-20",
        zodpovedny: "Zhotovitel",
        status: "otevreno",
        popis: "Provede 2× vzorek omítky: štuková / sádrová stěrka + malba dle zadání, do 20.6. ▸ 26.5: upřesnit typ omítky, potvrdit platnost interiérů. KEIM dodá typ a materiál pro vzorky – ZHOT se propojí s KEIM ohledně objednávky.",
      },
      {
        id: "3.9",
        termin: "2026-05-19",
        zodpovedny: "AD",
        status: "trva",
        popis: "AD zkonzultuje spotřebiče v kuchyňské lince (voda, odpady, elektro). Zhotovitel ověří provedení na základě vybraných spotřebičů. ▸ 26.5: TRVÁ.",
      },
      {
        id: "3.10",
        termin: "2026-05-19",
        zodpovedny: "AD + INV",
        status: "otevreno",
        popis: "AD + INV potvrdí povrchy – koupelny i ostatní. Platí PD, nebo upřesnění? ▸ 26.5: obstarat vzorky dle PD. AD zadá stěrky (typ, barevnost). Vzorky keramiky a vnitřních povrchů zajistí stavba.",
      },
      {
        id: "3.11",
        termin: "2026-05-19",
        zodpovedny: "Zhotovitel",
        status: "splneno",
        popis: "Polohy koncových prvků ZTI, UT a ELE dle PD interiéru. ▸ 26.5: provádí se, vypouští se ze sledování.",
      },
      {
        id: "3.12",
        termin: "2026-05-19",
        zodpovedny: "Zhotovitel",
        status: "otevreno",
        popis: "Světla bez provedení kabeláží 5×1,5. ▸ 26.5: 1. NP již provedeno v 3×1,5 – úkol platí pro 1. PP (kabeláž 5×1,5).",
      },
      {
        id: "3.13",
        termin: "2026-05-19",
        zodpovedny: "Zhotovitel",
        status: "otevreno",
        popis: "Alternativa ke světlíku v pracovně – předložena pouze úspora, prosíme o nabídku jiného dodavatele. ▸ 26.5: poptávka zaslána firmě Značková okna.",
      },
      {
        id: "3.14",
        termin: "2026-05-19",
        zodpovedny: "AD + INV",
        status: "otevreno",
        popis: "AD + INV vyberou odstíny fasád a strukturu, zhotovitel provede vzorky. ▸ 26.5: KEIM dodá typ a materiál – ZHOT se propojí s KEIM ohledně objednávky a logistiky.",
      },
      {
        id: "3.15",
        termin: "2026-05-19",
        zodpovedny: "Zhotovitel",
        status: "otevreno",
        popis: "Vnitřní schody – vyjasnit objednávku. ▸ 26.5: zatím pouze CN JAP. ZHOT objedná technika na zaměření a kontrolu dle PD. Pokud nevyhovuje, provede se dle PD INT.",
      },
      {
        id: "3.16",
        termin: "2026-05-19",
        zodpovedny: "AD + INV",
        status: "trva",
        popis: "Venkovní rozvody elektro – specifikace okruhů světel, ovládání, zásuvky pro zahradu (sekačka, závlaha, vířivka, bazén, gril…). ▸ 26.5: TRVÁ.",
      },
      {
        id: "3.17",
        termin: "2026-05-19",
        zodpovedny: "Zhotovitel + AD",
        status: "trva",
        popis: "Kontrola objednaných oken – rozměry a napojení na ostatní kce. ▸ 26.5: OK – TRVÁ.",
      },
      {
        id: "3.18",
        termin: "2026-05-19",
        zodpovedny: "Zhotovitel + AD",
        status: "trva",
        popis: "Konzultace s dodavatelem dveří, sondy pro zasekání zárubní v monolitu (bez přerušení výztuže). ▸ 26.5: předběžně domluvena účast dodavatele na příštím KD – objedná ZHOT. TRVÁ.",
      },
    ],
  },

  // ── KD 2 – 26. 5. 2026 ───────────────────────────────────────────────────
  {
    id: "kd-2026-05-26",
    cislo: 2,
    datum: "2026-05-26",
    pritomni: [
      { role: "INV", jmeno: "manželé Pěchoučkovi" },
      { role: "AD",  jmeno: "Ing. Arch. Jakub Žák" },
      { role: "TDI", jmeno: "Jakub Bednář" },
      { role: "TDI", jmeno: "Jan Nekola", kontakt: "737 283 324" },
      { role: "Zhotovitel", jmeno: "Michal Lohoyda" },
    ],
    prubehy: [
      "Provádí se: vyzdívání příček, montáž hrubých rozvodů ZTI, montáž HI soklu, parotěsné zábrany střechy, rozvody ELEKTRO",
      "Následné práce: vyzdívky příček, rozvody ELEKTRO",
      "BOZP: kontrola zábradlí, otvory ve stropu a úklid – OK",
    ],
    zmeny: [
      "Světlík: poptávka odeslána firmě Značková okna",
      "25.5: zaslán dotaz objednateli na platnost interiérů",
      "Kabeláž pro trafa do rozvaděče – navíc rozvaděč = větší",
      "Vyjma 1. NP všude kabel 5×1,5 místo 3×1,5",
    ],
    ukoly: [],
  },
];
