const PROJEKT = {
  nazev: "Rekonstrukce a přestavba rodinného domu – Podolanka",
  investor: "manželé Pěchoučkovi",
};

const ZAPISKY = [
  // ── KD 1 – 19. 5. 2026 ───────────────────────────────────────────────────
  {
    id: "kd-2026-05-19",
    cislo: 1,
    datum: "2026-05-19",
    pritomni: [
      { role: "INV", jmeno: "manželé Pěchoučkovi" },
      { role: "AD",  jmeno: "Ing. Arch. Jakub Žák" },
      { role: "TDI", jmeno: "Jakub Bednář" },
      { role: "TDI", jmeno: "Jan Nekola", kontakt: "737 283 324" },
      { role: "Zhotovitel", jmeno: "Michal Lohoyda" },
    ],
    prubehy: [
      "Provádí se: vyzdívání příček, montáž hrubých rozvodů ZTI",
      "Následné práce: betonáž stropu – dokončení, hydroizolace střechy, vyzdívky příček, rozvody ZTI",
      "BOZP: nutno kontrolovat zábradlí, otvory ve stropu a úklid",
    ],
    zmeny: [
      "Změna rozměrů interiérových dveří",
      "Poptat změnu světlíku",
      "Vyjasněn rozpor mezi PD ARCH a STAT ohledně použitých materiálů",
    ],
    ukoly: [
      {
        id: "3.1",
        termin: "2026-06-07",
        zodpovedny: "Zhotovitel",
        status: "trva",
        popis: "Předloží aktualizovaný HMG s následným postupem prací. Fáze stavby neodpovídá smluveným termínům – RPT z 22.3.2026 nesplněn. Na KD 26.5. zhotovitel potvrdil, že si je situace vědom.",
        dalsiKrok: "Zhotovitel dodá aktualizovaný harmonogram postupu prací nejpozději do 7.6.2026.",
      },
      {
        id: "3.3",
        termin: "2026-04-28",
        zodpovedny: "Zhotovitel",
        status: "splneno",
        popis: "U plotu na záp. straně zjištěno kanalizační vedení od sousedního objektu – hrozila kolize s oplocením.",
        dalsiKrok: "Úkol zrušen: jde o staré potrubí souseda z doby výstavby, lze likvidovat – kolize s oplocením odpadá.",
      },
      {
        id: "3.4",
        termin: "2026-04-28",
        zodpovedny: "TDI / AD",
        status: "splneno",
        popis: "Zhotovitel se dotazoval na způsob ukončení drenáže okolo objektu.",
        dalsiKrok: "Vyřešeno: drenáž bude provedena dle PD a ukončena pod opěrnou stěnou.",
      },
      {
        id: "3.5",
        termin: "2026-04-28",
        zodpovedny: "AD",
        status: "splneno",
        popis: "AD doplnil přesné pozice koncových prvků ZTI a elektro.",
        dalsiKrok: "Splněno: pozice doplněny do pohledů PD. V případě nejasností zašle zhotovitel dotaz AD.",
      },
      {
        id: "3.6",
        termin: "2026-05-19",
        zodpovedny: "Zhotovitel",
        status: "otevreno",
        popis: "Rozvody ZTI – kanalizace provedena nesprávně: redukce zkrácenou místo klasickou metodou, izolace neprovedeny v celém rozsahu. Materiál vody zaměněn od Viega na Concept. Kotvení potrubí neodpovídá TL výrobce.",
        dalsiKrok: "Zhotovitel potvrdil nápravu (2.6: „OK napravíme"). Doplnění: excentrické redukce v ležatém potrubí instalovat rovným povrchem nahoře. Zhotovitel doloží provedení všech oprav: (1) klasické redukce, (2) izolace v plném rozsahu, (3) tech. parametry Viega vs. Concept, (4) kotvení a izolace v objímkách.",
      },
      {
        id: "3.7",
        termin: "2026-05-19",
        zodpovedny: "Zhotovitel",
        status: "splneno",
        popis: "Otvory skrz ŽB konstrukce provádět dle PD pouze odvrty. Prostupy a rozvody na podkladu dokumentace DPS a INT současně.",
        dalsiKrok: "Splněno: prostupy zabetonovány. Případné další prostupy budou řešeny dle potřeby.",
      },
      {
        id: "3.8",
        termin: "2026-06-20",
        zodpovedny: "Zhotovitel",
        status: "otevreno",
        popis: "Zhotovitel provede 2× vzorek omítky: štuková omítka / sádrová stěrka + malba dle zadání. Termín vzorků do 20.6.",
        dalsiKrok: "Zhotovitel se propojí s firmou KEIM ohledně dodání materiálu pro vzorky. Před objednávkou potvrdit typ omítky a platnost interiérového projektu (viz samostatná komunikace).",
      },
      {
        id: "3.9",
        termin: "2026-05-19",
        zodpovedny: "AD",
        status: "trva",
        popis: "AD zkonzultuje výběr spotřebičů v kuchyňské lince pro ověření správnosti rozvodů voda, odpady a elektro.",
        dalsiKrok: "28.5. zaslán vývodový plán instalací od dodavatele kuchyně. Stále otevřeno: nutno dořešit provedení odtahu digestoře na fasádě – AD upřesní řešení, zhotovitel upraví rozvody.",
      },
      {
        id: "3.10",
        termin: "2026-05-19",
        zodpovedny: "AD + INV",
        status: "otevreno",
        popis: "AD + INV potvrdí povrchové úpravy – zejména koupelny, ale i ostatní místnosti. Upřesnění, zda platí PD nebo jsou změny.",
        dalsiKrok: "AD zadá konkrétní stěrky (typ a barevnost). Stavba zajistí vzorky keramiky a vnitřních povrchů. Specifikace v projektu INT včetně ref. výrobců – AD zašle seznam v samostatném mailu.",
      },
      {
        id: "3.11",
        termin: "2026-05-19",
        zodpovedny: "Zhotovitel",
        status: "splneno",
        popis: "Zhotovitel provádí polohy koncových prvků ZTI, UT a ELE dle PD interiéru.",
        dalsiKrok: "Splněno: úkol se vypouští ze sledování, zhotovitel pokračuje průběžně dle PD.",
      },
      {
        id: "3.12",
        termin: "2026-05-19",
        zodpovedny: "Zhotovitel",
        status: "splneno",
        popis: "Veškerá světla bez provedené kabeláže budou provedena kabelem 5×1,5. Upřesnění (26.5): 1. NP již provedeno v 3×1,5 – tento úkol platí pouze pro 1. PP.",
        dalsiKrok: "Splněno (2.6.2026): kabeláž světel v 1. PP kabelem 5×1,5 provedena. Úkol se vypouští ze sledování.",
      },
      {
        id: "3.13",
        termin: "2026-05-19",
        zodpovedny: "Zhotovitel",
        status: "otevreno",
        popis: "Ověřit alternativu ke světlíku v pracovně – dosud předložena pouze úspora ve stávající nabídce, nikoliv nabídka jiného dodavatele.",
        dalsiKrok: "Zhotovitel vyčká na cenovou nabídku od firmy Značková okna (poptávka odeslána 26.5.). Stav 2.6: CN dosud nedoručena, úkol stále trvá. Po obdržení CN předloží INV k rozhodnutí.",
      },
      {
        id: "3.14",
        termin: "2026-05-19",
        zodpovedny: "AD + INV",
        status: "otevreno",
        popis: "AD + INV vyberou odstíny a strukturu fasád, zhotovitel následně provede vzorky.",
        dalsiKrok: "AD + INV potvrdí typ fasády (viz samostatná komunikace). KEIM dodá materiál pro vzorky – zhotovitel se propojí s KEIM ohledně objednávky a logistiky.",
      },
      {
        id: "3.15",
        termin: "2026-05-19",
        zodpovedny: "Zhotovitel",
        status: "otevreno",
        popis: "Vnitřní schody – vyjasnit stav objednávky. Dosud pouze CN od firmy JAP.",
        dalsiKrok: "Zhotovitel objedná technika na zaměření a kontrolu připravenosti stavby dle PD. Pokud nesplňuje požadavky, schody se provedou dle PD INT.",
      },
      {
        id: "3.16",
        termin: "2026-05-19",
        zodpovedny: "AD + INV",
        status: "trva",
        popis: "Venkovní rozvody elektro – chybí návrh specifikace: okruhy světel, systém a pozice ovládání, zásuvky pro zahradu (sekačka, závlaha, vířivka, bazén, gril…).",
        dalsiKrok: "AD + INV definují a odsouhlasí specifikaci venkovního elektra, AD zpracuje zadání pro zhotovitele.",
      },
      {
        id: "3.17",
        termin: "2026-05-19",
        zodpovedny: "Zhotovitel + AD",
        status: "trva",
        popis: "Fyzická kontrola objednaných oken – ověření shody s PD (rozměry, napojení na ostatní kce).",
        dalsiKrok: "Zhotovitel + AD provedou kontrolu objednaných oken oproti PD a doloží výsledek (případné odchylky ihned řeší s výrobcem).",
      },
      {
        id: "3.18",
        termin: "2026-05-19",
        zodpovedny: "Zhotovitel + AD",
        status: "trva",
        popis: "Konzultace s dodavatelem dveří ohledně otvorů. Sondy pro zasekání zárubní v monolitické konstrukci – bez přerušení výztuže.",
        dalsiKrok: "Sondy provedeny (2.6.2026) – zjištěna možná úprava konstrukce. Zhotovitel zajistí návštěvu dodavatele dveří na stavbě za účelem zaměření a potvrzení řešení zárubní.",
      },
    ],
  },

  // ── KD 2 – 26. 5. 2026 ───────────────────────────────────────────────────
  {
    id: "kd-2026-05-26",
    cislo: 2,
    datum: "2026-05-26",
    pritomni: [
      { role: "INV", jmeno: "manželé Pěchoučkovi" },
      { role: "AD",  jmeno: "Ing. Arch. Jakub Žák" },
      { role: "TDI", jmeno: "Jakub Bednář" },
      { role: "TDI", jmeno: "Jan Nekola", kontakt: "737 283 324" },
      { role: "Zhotovitel", jmeno: "Michal Lohoyda" },
    ],
    prubehy: [
      "Provádí se: vyzdívání příček, montáž hrubých rozvodů ZTI, montáž HI soklu, parotěsné zábrany střechy, rozvody ELEKTRO",
      "Následné práce: vyzdívky příček, rozvody ELEKTRO",
      "BOZP: kontrola zábradlí, otvory ve stropu a úklid – OK",
    ],
    zmeny: [
      "Světlík: poptávka odeslána firmě Značková okna",
      "25.5: zaslán dotaz objednateli na platnost interiérů",
      "Kabeláž pro trafa do rozvaděče – navíc rozvaděč = větší",
      "Vyjma 1. NP všude kabel 5×1,5 místo 3×1,5",
    ],
    ukoly: [],
  },

  // ── KD 3 – 2. 6. 2026 ────────────────────────────────────────────────────
  {
    id: "kd-2026-06-02",
    cislo: 3,
    datum: "2026-06-02",
    pritomni: [
      { role: "INV", jmeno: "manželé Pěchoučkovi" },
      { role: "AD",  jmeno: "Ing. Arch. Jakub Žák" },
      { role: "TDI", jmeno: "Jakub Bednář" },
      { role: "TDI", jmeno: "Jan Nekola", kontakt: "737 283 324" },
      { role: "Zhotovitel", jmeno: "Michal Lohoyda" },
    ],
    prubehy: [
      "Provádí se: vyzdívání příček, montáž HI soklu, parotěsné zábrany střechy, rozvody ELEKTRO",
      "Následné práce: rozvody ELEKTRO, SLABOPROUD, EZS apod.",
      "BOZP: nutno kontrolovat zábradlí, otvory ve stropu a úklid – OK",
    ],
    zmeny: [
      "Poptávka světlíku u Značková okna – probíhá",
      "25.5: zaslán dotaz objednateli na platnost interiérů",
      "Kabeláž pro trafa do rozvaděče – navíc rozvaděč = větší",
      "Vyjma 1. NP všude kabel 5×1,5 místo 3×1,5",
    ],
    ukoly: [],
  },
];
